version: '3.8'
services:
  api:
    image: golang:alpine3.18
    container_name: api
    env_file: .env
    volumes:
      - .:/opt/app/api
    working_dir: /opt/app/api
    command: go run ./cmd/app/main.go
    networks:
      - external_network
      - internal_network
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: on-failure

  pgbouncer:
    restart: always
    image: bitnami/pgbouncer:1.20.0
    container_name: pgbouncer
    env_file: .env
    environment:
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASS}
      POSTGRESQL_DATABASE: ${DB_NAME}
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT: 5432
      PGBOUNCER_PORT: 6432
      PGBOUNCER_BIND_ADDRESS: 0.0.0.0
      PGBOUNCER_CLIENT_TLS_SSLMODE: disable
      # PGBOUNCER_CLIENT_TLS_CERT_FILE: /opt/bitnami/pgbouncer/certs/pgbouncer.crt
      # PGBOUNCER_CLIENT_TLS_KEY_FILE: /opt/bitnami/pgbouncer/certs/pgbouncer.key
    networks:
      - internal_network
    volumes:
    #   - /path/to/certs:/opt/bitnami/pgbouncer/certs
    - /etc/pgbouncer-persistence/conf/:/bitnami/pgbouncer/conf/

  db:
    restart: always
    image: postgres:14-alpine
    container_name: ${DB_HOST}
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgres14:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:7-alpine
    container_name: ${REDIS_HOST}
    env_file: .env
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data

networks:
  external_network:
  internal_network:
    internal: true