version: '3.8'
services:
  api:
    image: golang:alpine3.18
    container_name: api
    env_file: .env
    volumes:
      - .:/opt/app/api
    working_dir: /opt/app/api
    command: go run ./cmd/app/main.go
    networks:
      - external_network
      - internal_network
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: on-failure

  pgbouncer:
    restart: always
    image: edoburu/pgbouncer:1.19.1-p1
    container_name: pgbouncer
    env_file: .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      POOL_MODE: transaction
      ADMIN_USERS: ${DB_USER}
      AUTH_TYPE: scram-sha-256
      MAX_CLIENT_CONN: 200
      DEFAULT_POOL_SIZE: 25
    ports:
      - "5432:5432"
    networks:
      - internal_network
    depends_on:
      - db

  db:
    restart: always
    image: postgres:14-alpine
    container_name: ${DB_HOST}
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgres14:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:7-alpine
    container_name: ${REDIS_HOST}
    env_file: .env
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis:/data

networks:
  external_network:
  internal_network:
    internal: true